
jobs:
- job: A
  steps:
  - script: echo "##vso[task.setvariable variable=applicationId;isOutput=true]629ae9cb-95e0-46b7-8a88-a4034b68323e"
    name: mytask

- job: B
  variables:
    newValue: $[dependencies.A.outputs['mytask.applicationId']]
  dependsOn: A
  steps:
  - powershell: |
      Write-Host "This value is: ${{variables.newValue}}"
    displayName: 'Ouptut the value'
