
jobs:
- job: A
  steps:
  - script: echo "##vso[task.setvariable variable=applicationId;isOutput=true]629ae9cb-95e0-46b7-8a88-a4034b68323e"
    name: myvalue

- job: B
  variables:
    newValue: $[dependencies.A.outputs['myvalue.applicationId']]
  dependsOn: A
  steps:
  - script: echo the value is: $(newValue)
